/**
 * HelioTwin — Export Service
 *
 * PDF and CSV export for the Planning Report workspace.
 * PDF format follows engineering report conventions: section numbers,
 * tables, precise labelling. No decorative elements.
 */

import { buildReportData } from './analysisEngine.js';

// ── PDF EXPORT ───────────────────────────────────────────────────

export async function exportPDF(reportData, recommendations) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });

  const W = 210;
  const L = 20;  // left margin
  const R = W - 20; // right margin
  const CW = R - L; // content width

  let y = 20;

  const LINE_HT = 5;
  const SECTION_GAP = 8;
  const COL_GAY = 3;

  // ── Helper functions ──
  function checkPage(needed = 10) {
    if (y + needed > 277) { doc.addPage(); y = 20; }
  }

  function heading1(text) {
    checkPage(12);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(17, 24, 39);
    doc.text(text, L, y);
    y += LINE_HT + 2;
    doc.setDrawColor(209, 213, 219);
    doc.line(L, y, R, y);
    y += 4;
  }

  function heading2(text) {
    checkPage(8);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(75, 85, 99);
    doc.text(text, L, y);
    y += LINE_HT;
  }

  function body(text, indent = 0) {
    checkPage(6);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(55, 65, 81);
    const lines = doc.splitTextToSize(text, CW - indent);
    doc.text(lines, L + indent, y);
    y += lines.length * 4.2;
  }

  function metricRow(label, value, indent = 0) {
    checkPage(5);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    doc.text(label, L + indent, y);
    doc.setFont('courier', 'normal');
    doc.setTextColor(17, 24, 39);
    doc.text(String(value), L + indent + 60, y);
    y += 4.5;
  }

  function divider() { checkPage(4); y += 2; doc.setDrawColor(229, 231, 235); doc.line(L, y, R, y); y += 4; }
  function gap(n = SECTION_GAP) { y += n; }

  // ── HEADER ──
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(17, 24, 39);
  doc.text('HELIOTWIN PLANNING ANALYSIS REPORT', L, y);
  y += 7;

  doc.setFont('courier', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.text(`Reference: ${reportData.reference}`, L, y);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}`, R, y, { align: 'right' });
  y += 5;

  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(0.5);
  doc.line(L, y, R, y);
  doc.setLineWidth(0.2);
  y += 8;

  // ── SECTION 1: SITE INFORMATION ──
  heading1('SECTION 1 — SITE INFORMATION');
  metricRow('Location', reportData.site.location);
  metricRow('Coordinates', reportData.site.coordinates);
  metricRow('Study area', reportData.site.studyArea);
  metricRow('Analysis date', reportData.site.analysisDate);
  metricRow('Analysis window', reportData.site.analysisWindow);
  metricRow('Generated by', 'HelioTwin v1.0 — Solar calculations via SunCalc (Meeus algorithms)');
  gap();

  // ── SECTION 2: URBAN CONTEXT ──
  heading1('SECTION 2 — URBAN CONTEXT SUMMARY');
  const uc = reportData.urbanContext;
  if (uc.buildingCount) {
    metricRow('Total buildings', uc.buildingCount);
    metricRow('Average height', `${uc.avgHeight} m`);
    metricRow('Maximum height recorded', `${uc.maxHeight} m`);
    metricRow('Green cover (estimated)', `${uc.greenCover}%`);
    metricRow('Study area', `${uc.areaSqKm} km²`);
  } else {
    body('Urban context data not available. Complete the Urban Overview workspace.');
  }
  gap();

  // ── SECTION 3: SUNLIGHT ANALYSIS ──
  heading1('SECTION 3 — SUNLIGHT ANALYSIS');
  metricRow('Solar noon', reportData.sunlight.solarNoon);
  metricRow('Day length', reportData.sunlight.dayLength);
  metricRow('Maximum altitude', reportData.sunlight.maxAltitudeDeg);
  metricRow('Shadow ratio at solar noon', `${reportData.sunlight.shadowRatioNoon}× building height`);
  gap();

  // ── SECTION 4: ENVIRONMENTAL FINDINGS ──
  heading1('SECTION 4 — ENVIRONMENTAL FINDINGS');

  heading2('4.1 Prolonged Sun Exposure');
  if (reportData.insights.prolongedSun) {
    const ps = reportData.insights.prolongedSun;
    metricRow('Daily solar exposure', `${ps.dailySunHours} h/day`, 4);
    metricRow('Applied threshold', `> ${ps.thresholdHours} h/day`, 4);
    metricRow('Excess exposure', `${ps.excessHours} h above threshold`, 4);
    metricRow('Affected open area', `${ps.affectedAreaSqKm} km² (${ps.affectedAreaPct}% of study zone)`, 4);
  } else { body('Not computed.', 4); }
  gap(4);

  heading2('4.2 Shade Deficiency Analysis');
  if (reportData.insights.shadeDeficiency) {
    const sd = reportData.insights.shadeDeficiency;
    metricRow('Public spaces assessed', sd.totalPublicSpaces, 4);
    metricRow('Shade threshold applied', `< ${sd.thresholdHours} h/day`, 4);
    metricRow('Deficient spaces identified', sd.deficientSpaces, 4);
    if (sd.spaces && sd.spaces.length > 0) {
      gap(2);
      body('Deficient spaces (listed by shade duration):', 4);
      sd.spaces.forEach(s => {
        metricRow(s.name, `${s.shadeHours} h shade/day`, 8);
      });
    }
  } else { body('Not computed.', 4); }
  gap(4);

  heading2('4.3 Vegetation Opportunity');
  if (reportData.insights.vegetation) {
    const veg = reportData.insights.vegetation;
    metricRow('Identified corridors', veg.locationCount, 4);
    metricRow('Total street length', `${veg.totalLengthM} m`, 4);
  } else { body('Not computed.', 4); }
  gap(4);

  heading2('4.4 Solar Rooftop Potential');
  if (reportData.insights.solarPotential) {
    const sp = reportData.insights.solarPotential;
    metricRow('Total buildings assessed', sp.totalBuildings, 4);
    metricRow('High (> 1400 kWh/m²/yr)', sp.tiered.High, 4);
    metricRow('Good (1100–1400 kWh/m²/yr)', sp.tiered.Good, 4);
    metricRow('Moderate (800–1100 kWh/m²/yr)', sp.tiered.Moderate, 4);
    metricRow('Low (< 800 kWh/m²/yr)', sp.tiered.Low, 4);
    metricRow('Base annual irradiance', `${sp.annualIrradianceBase} kWh/m²/yr`, 4);
  } else { body('Not computed.', 4); }
  gap();

  // ── SECTION 5: SCENARIO COMPARISON ──
  heading1('SECTION 5 — SCENARIO COMPARISON');
  if (reportData.scenario) {
    const sc = reportData.scenario;
    body('Comparison: Scenario A (Baseline) vs Scenario B (Proposed development)');
    gap(2);
    heading2('Metric comparison');
    metricRow('Shadow coverage — Baseline', `${sc.baseline.shadowCoveragePct}%`, 4);
    metricRow('Shadow coverage — Proposed', `${sc.proposed.shadowCoveragePct}%`, 4);
    metricRow('Shadow coverage change', `+${sc.delta.shadowCoveragePct}pp`, 4);
    gap(2);
    metricRow('Daily sunlight hours — Baseline', `${sc.baseline.sunlightHours} h`, 4);
    metricRow('Daily sunlight hours — Proposed', `${sc.proposed.sunlightHours} h`, 4);
    metricRow('Sunlight change', `${sc.delta.sunlightHoursChange} h/day`, 4);
    gap(2);
    metricRow('Affected neighbouring structures', sc.delta.affectedNeighbours, 4);
    metricRow('Average exposure reduction', `${sc.delta.avgExposureReduction} h/day`, 4);
    metricRow('Worst-case reduction', `${sc.delta.worstCaseReduction} h/day`, 4);
  } else {
    body('Scenario comparison not completed.');
  }
  gap();

  // ── SECTION 6: RECOMMENDATIONS ──
  heading1('SECTION 6 — PLANNING RECOMMENDATIONS');
  const recText = recommendations || reportData.recommendations;
  if (recText) {
    const paragraphs = recText.split('\n\n');
    paragraphs.forEach(p => { body(p); gap(2); });
  } else {
    body('No recommendations recorded.');
  }

  // ── FOOTER ──
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont('courier', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(156, 163, 175);
    doc.text(`HelioTwin Planning Analysis Report — ${reportData.reference}`, L, 290);
    doc.text(`Page ${i} of ${pageCount}`, R, 290, { align: 'right' });
    doc.text('Solar position data: SunCalc.js (Meeus Astronomical Algorithms) — Building data: OpenStreetMap contributors', L, 294);
  }

  doc.save(`HelioTwin_${reportData.reference}.pdf`);
}

// ── CSV EXPORT ───────────────────────────────────────────────────

export function exportCSV(reportData) {
  const rows = [
    ['HelioTwin Planning Analysis Report'],
    ['Reference', reportData.reference],
    ['Generated', new Date().toISOString()],
    [],
    ['SITE INFORMATION'],
    ['Location', reportData.site.location],
    ['Coordinates', reportData.site.coordinates],
    ['Study Area', reportData.site.studyArea],
    ['Analysis Date', reportData.site.analysisDate],
    [],
    ['URBAN CONTEXT'],
    ['Building Count', reportData.urbanContext.buildingCount || ''],
    ['Average Height (m)', reportData.urbanContext.avgHeight || ''],
    ['Maximum Height (m)', reportData.urbanContext.maxHeight || ''],
    ['Green Cover (%)', reportData.urbanContext.greenCover || ''],
    ['Study Area (km²)', reportData.urbanContext.areaSqKm || ''],
    [],
    ['SUNLIGHT ANALYSIS'],
    ['Solar Noon', reportData.sunlight.solarNoon],
    ['Day Length', reportData.sunlight.dayLength],
    ['Max Sun Altitude', reportData.sunlight.maxAltitudeDeg],
    ['Shadow Ratio at Noon', reportData.sunlight.shadowRatioNoon],
    [],
    ['ENVIRONMENTAL FINDINGS'],
  ];

  if (reportData.insights.prolongedSun) {
    const ps = reportData.insights.prolongedSun;
    rows.push(
      ['Prolonged Sun Exposure — Daily Hours (h)', ps.dailySunHours],
      ['Prolonged Sun Exposure — Threshold (h)', ps.thresholdHours],
      ['Prolonged Sun Exposure — Affected Area (km²)', ps.affectedAreaSqKm],
      ['Prolonged Sun Exposure — Affected Area (%)', ps.affectedAreaPct],
    );
  }

  if (reportData.insights.shadeDeficiency) {
    const sd = reportData.insights.shadeDeficiency;
    rows.push(
      ['Shade Deficiency — Public Spaces Assessed', sd.totalPublicSpaces],
      ['Shade Deficiency — Deficient Spaces', sd.deficientSpaces],
      ['Shade Deficiency — Shade Duration (h)', sd.shadeHours],
    );
  }

  if (reportData.insights.solarPotential) {
    const sp = reportData.insights.solarPotential;
    rows.push(
      ['Solar Potential — Total Buildings', sp.totalBuildings],
      ['Solar Potential — High Suitability', sp.tiered.High],
      ['Solar Potential — Good Suitability', sp.tiered.Good],
      ['Solar Potential — Moderate Suitability', sp.tiered.Moderate],
      ['Solar Potential — Low Suitability', sp.tiered.Low],
      ['Solar Potential — Base Annual Irradiance (kWh/m²/yr)', sp.annualIrradianceBase],
    );
  }

  if (reportData.scenario) {
    const sc = reportData.scenario;
    rows.push(
      [],
      ['SCENARIO COMPARISON'],
      ['Shadow Coverage — Baseline (%)', sc.baseline.shadowCoveragePct],
      ['Shadow Coverage — Proposed (%)', sc.proposed.shadowCoveragePct],
      ['Shadow Coverage — Delta (pp)', sc.delta.shadowCoveragePct],
      ['Affected Neighbouring Structures', sc.delta.affectedNeighbours],
      ['Average Exposure Reduction (h/day)', sc.delta.avgExposureReduction],
      ['Worst-Case Reduction (h/day)', sc.delta.worstCaseReduction],
    );
  }

  const csvContent = rows.map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(',')).join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `HelioTwin_${reportData.reference}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}
